projectMiWeb/main/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('posts/', views.posts_page, name='posts_page'),
    path('interested/', views.interested_page, name='interested_page'),
    path('following/', views.following_page, name='following_page'),
    path('post/<int:post_id>/', views.show_post, name='post'),
    path('category/<int:cat_id>/', views.show_category, name='category'),
]

projectMiWeb/projectMiWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectMiWeb/main/models.py
from django.db import models
from django.urls import reverse


class Posts(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField(null=True)
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=15)
    cat = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title}{self.pk}"

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def get_absolute_url(self):
        return reverse('post',kwargs={'post_id': self.pk})


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category',kwargs={'cat_id': self.pk})

projectMiWeb/main/views.py
from django.http import Http404
from django.shortcuts import render,HttpResponse
from .models import Posts, Category


def home_page(request):
    return render(request,'main/index.html')


def posts_page(request):
    posts = Posts.objects.all()
    return render(request,'main/posts_page.html', {'posts': posts})


def interested_page(request):
    return render(request,'main/interested.html', {'cat_selected':0})


def following_page(request):
    return render(request,'main/following_page.html')


def show_post(request, post_id):
    post = Posts.objects.get(id=post_id)
    return render(request,'main/post_detail.html',{'post_id': post_id,'post': post})


def show_category(request, cat_id):
    posts = Posts.objects.filter(cat_id=cat_id)
    cat_name = Category.objects.get(id=cat_id)
    if len(posts) == 0:
        raise Http404()
    return render(request,'main/category_detail.html',{'cat_id': cat_id, 'posts': posts, 'cat_selected':cat_id, 'cat_name':cat_name})

projectMiWeb/main/templates/main/base.html
{% load static %}
{% load main_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
</head>
<body>

    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <li><div class="logo">mi<span>Web</span></div></li>
        <li><a href="{% url 'home_page' %}" class="nav-link px-2 link-secondary">Главная</a></li>
        <li><a href="{% url 'posts_page' %}" class="nav-link px-2 link-dark">Посты</a></li>
        <li><a href="{% url 'interested_page' %}" class="nav-link px-2 link-dark">Аккаунт</a></li>
      </ul>
      <div class="col-md-3 text-end">
        <button type="button" class="btn btn-outline-primary me-2">Login</button>
        <button type="button" class="btn btn-primary">Sign-up</button>
      </div>
    </header>
<div class="wrapper">
    <div class="category">
            {% if cat_selected == 0 %}
                <h2>Все Интересы</h2>
            {% else %}
                <h2><a class="btn btn-secondary btn-lg" href="{% url 'posts_page' %}">Все интересы</a></h2>
            {% endif %}

            {% show_categories cat_selected %}
    </div>
        {% block content %}

        {% endblock content %}
</div>
</body>
</html>

projectMiWeb/main/templates/main/category_detail.html
{% extends 'main/base.html' %}
{% load main_tags %}
{% block title%}Страница с категориями{% endblock title%}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <h3 class="title">{{ post.title }}</h3><br>
            {% autoescape on %}
                <p class="desc">
                    {{ post.description| slice:":100" }}.. <a class="btn btn-primary btn-sm" role="button" href="{{ post.get_absolute_url }}">Читать пост</a>
                </p>
            {% endautoescape %}
        </div>
    {% endfor %}
{% endblock content %}

projectMiWeb/main/templates/main/following_page.html
{% extends 'main/base.html' %}
{% block title %}Страница подписчиков{% endblock title %}

{% block content %}

{% endblock content %}

projectMiWeb/main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}Главная страница{% endblock title %}

{% block content %}
{% endblock content %}

projectMiWeb/main/templates/main/interested.html
{% extends 'main/base.html' %}

{% block title %}Инт{% endblock title %}

{% block content %}
<div class="category">

        </div>
{% endblock content %}

projectMiWeb/main/templates/main/list_categories.html
{% for cat in cats %}
      {% if cat.posts_set.exists %}
      {% if cat.pk == cat_selected %}
            <h4 class="btn btn-primary btn-lg">{{ cat }}</h4>
            {% else %}
                <h4><a class="btn btn-secondary btn-lg" href="{{ cat.get_absolute_url }}">{{ cat }}</a></h4>
         {% endif %}
        {% else %}
      {% endif %}

{% endfor %}

projectMiWeb/main/templates/main/post_detail.html
{% extends 'main/base.html' %}
{% block title %}Post detail{% endblock title %}

{% block content %}
    <div class="post">
            <h3 class="title">{{ post.title }}</h3><br>
            {% autoescape on %}
                <p class="desc">
                    {{ post.description}} <a class="btn btn-danger btn-sm" role="button" href="{% url 'posts_page' %}">Вернуться</a>
                </p>
            {% endautoescape %}
            <a class="btn btn-secondary btn-sm" href="{{ post.cat.get_absolute_url }}">{{ post.cat }}</a>
    </div>

{% endblock content %}

projectMiWeb/main/templates/main/posts_page.html
{% extends 'main/base.html' %}
{% block title %}Страница с постами{% endblock title %}

{% block content %}

        {% for post in posts %}
            <div class="post">
                <h3 class="title">{{ post.title }}</h3><br>
                {% autoescape on %}
                    <p class="desc">
                        {{ post.description| slice:":100" }}.. <a class="btn btn-primary btn-sm" role="button" href="{{ post.get_absolute_url }}">Читать пост</a>
                    </p>
                {% endautoescape %}
                <a class="btn btn-secondary btn-sm" href="{{ post.cat.get_absolute_url }}">{{ post.cat }}</a>
            </div>
        {% endfor %}

{% endblock content %}